/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HOLA_H_RPCGEN
#define _HOLA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define HOLA_PROG 0x20000001
#define HOLA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HOLA 1
extern  char ** hola_1(void *, CLIENT *);
extern  char ** hola_1_svc(void *, struct svc_req *);
extern int hola_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HOLA 1
extern  char ** hola_1();
extern  char ** hola_1_svc();
extern int hola_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HOLA_H_RPCGEN */
