/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Hola.h"

char **
hola_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	
	 */

printf("Solicitud recibida\n");
 result = "Hola mundo";
	return &result;
}
