# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service_python.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66ile_service_python.proto\x12\tfileshare\"?\n\tFileChunk\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_size\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"+\n\x0cUploadStatus\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2H\n\x0b\x46ileService\x12\x39\n\x06Upload\x12\x14.fileshare.FileChunk\x1a\x17.fileshare.UploadStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_python_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILECHUNK']._serialized_start=40
  _globals['_FILECHUNK']._serialized_end=103
  _globals['_UPLOADSTATUS']._serialized_start=105
  _globals['_UPLOADSTATUS']._serialized_end=148
  _globals['_FILESERVICE']._serialized_start=150
  _globals['_FILESERVICE']._serialized_end=222
# @@protoc_insertion_point(module_scope)
